### ISSUE TITLE
production ready?

### ISSUE THREAD

**Issue by kolinfluence** [davidcoles/vc5#2]
1. production ready?
2. possible to make this as simple as possible so can be used as a package too without any / much dependencies?
3. what is this mainly used for?
4. any production use case / case studies?

**Comment by davidcoles** [comment]
1) production ready-ish
2) the only dependency is libbpf
3) load-balancing
4) not yet, but it seems to work in production (see stats in README)

**Comment by kolinfluence** [comment]
@davidcoles extremely interesting! thx for the great work. seems a lot of potential to be a mainstream lb.

is it possible to have cross datacenter as the backend for the lb in dsr mode?

how can i help? i'm amateur golang and c coder.

i've looked into this before coming across ur github
https://github.com/bparli/convey

i was looking at af_xdp too but because your documentation is extremely "limited / vague", so not sure if af_xdp is in the roadmap etc.

i'm mostly interested in pure bpf/xdp - af_xdp / tc kind of dsr lb.
totally new and exploring your repo, so pls bear with my newbie questions. thx by the way for taking it this far. 
coz i think it's very useful.

**Comment by davidcoles** [comment]
Thanks for the kind words @kolinfluence :-)

Cross datacentre would be difficult - as it is a Layer 2 balancer the LB needs to have an interface (either a NIC or a VLAN tagged virtual interface) on the same VLAN as the backends. So you would have to have a VLAN spanning datacentres.

I might add an L3 mode at some point in the future, but then it needs GRE/IP-IP tunnelling (or using DSCP values to indicate the VIP). Currently the focus is on replacing legacy L2LB appliances.

I have looked at convey before - I will need to have a read to remind myself about it ...

I'm not really too up on AF_XDP (again, I'll need to read up), but that gives you a userspace kernel-bypass kind of setup, if I'm not wrong. I think I just settled on loading eBPF into the kernel as it seemed the most efficient way of dealing with things. I could be wrong of course.

> i'm mostly interested in pure bpf/xdp - af_xdp / tc kind of dsr lb.

Would you mind elaborating on this - what's the goal?

Happy to answer any questions - sometimes it's the best way to get some useful documentation. Please feel free to ask away!

In terms of helping, questions, your real-world experience of running the software and suggestions as to features would be really useful. If you have an environment where you can create some high load test traffic then definitely let me know!

**Comment by davidcoles** [comment]
A couple of things that would be a really big help:

* what sort of workload are you using/thinking of using it for (L7 protocol, concurrents, bandwidth)
* what documentation would be most useful to you right now

FTI; I'm just adding some provision for DDoS mitigation - have only added stats collection atm (see the new utility) but I will add early drop filtering shortly.

**Comment by davidcoles** [comment]
CLosing as it has been idle for a month. Feel free to open a new issue if you have more questions though.
