### ISSUE TITLE
is there a way to route to backend nodes based upon X-REAL-IP or cloudflare-ip?

### ISSUE THREAD

**Issue by hiqsociety** [davidcoles/vc5#3]
cloudflare puts ip as cloudflare-ip. would like to route to the backend processing the ip with this vc5.

is there a way to do so?

**Comment by davidcoles** [comment]
Direct Server Return does not change the source IP of the the client so there is no need to do this.

**Comment by davidcoles** [comment]
I think that I mis-read this. However, as this load-balancer works only with layer3+4 information (IP address and port numbers) it does not inspect application level information like HTTP headers, so it is not able to make any decisions on that data. Something like HAProxy in HTTP mode may be more what you are looking for.
